"""empty message

Revision ID: 1155b696e7f3
Revises: 2c1d4530afc8
Create Date: 2023-02-28 13:58:01.253354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1155b696e7f3'
down_revision = '2c1d4530afc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friend',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_user_id', sa.Integer(), nullable=True),
    sa.Column('friend_user_id', sa.Integer(), nullable=True),
    sa.Column('cadence', sa.Integer(), nullable=True),
    sa.Column('provided_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['friend_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('friend', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_friend_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_friend_updated_at'), ['updated_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friend', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_friend_updated_at'))
        batch_op.drop_index(batch_op.f('ix_friend_created_at'))

    op.drop_table('friend')
    # ### end Alembic commands ###
