"""empty message

Revision ID: 1167cac77d8a
Revises: d2cec9a9d00c
Create Date: 2023-04-17 16:42:27.065897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1167cac77d8a'
down_revision = 'd2cec9a9d00c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hang', schema=None) as batch_op:
        batch_op.add_column(sa.Column('connect_type', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_hang_connect_type'), ['connect_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hang', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hang_connect_type'))
        batch_op.drop_column('connect_type')

    # ### end Alembic commands ###
