"""empty message

Revision ID: 223178149082
Revises: 4fd08e95bb1b
Create Date: 2023-04-25 09:35:51.196396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '223178149082'
down_revision = '4fd08e95bb1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invite_code', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('invite_code')

    # ### end Alembic commands ###
