"""empty message

Revision ID: 2c1d4530afc8
Revises: 5edc65f416c4
Create Date: 2023-02-27 18:37:40.858546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c1d4530afc8'
down_revision = '5edc65f416c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('user_type', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('max_hang_per_week', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_phone_number'), ['phone_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_user_type'), ['user_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_user_type'))
        batch_op.drop_index(batch_op.f('ix_user_phone_number'))
        batch_op.drop_column('created_at')
        batch_op.drop_column('max_hang_per_week')
        batch_op.drop_column('user_type')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
