"""empty message

Revision ID: 38af454e5f35
Revises: 64789e9258a4
Create Date: 2023-03-30 20:40:21.154018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38af454e5f35'
down_revision = '64789e9258a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fast_or_max', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('fast_or_max')

    # ### end Alembic commands ###
