"""empty message

Revision ID: 39dc8f3bb282
Revises: 1167cac77d8a
Create Date: 2023-04-17 16:51:34.923455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39dc8f3bb282'
down_revision = '1167cac77d8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hang', schema=None) as batch_op:
        batch_op.add_column(sa.Column('friend_type', sa.String(length=255), nullable=True))
        batch_op.drop_index('ix_hang_connect_type')
        batch_op.create_index(batch_op.f('ix_hang_friend_type'), ['friend_type'], unique=False)
        batch_op.drop_column('connect_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hang', schema=None) as batch_op:
        batch_op.add_column(sa.Column('connect_type', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_index(batch_op.f('ix_hang_friend_type'))
        batch_op.create_index('ix_hang_connect_type', ['connect_type'], unique=False)
        batch_op.drop_column('friend_type')

    # ### end Alembic commands ###
