"""empty message

Revision ID: 4fd08e95bb1b
Revises: 9117fac87e4b
Create Date: 2023-04-17 18:13:05.927070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fd08e95bb1b'
down_revision = '9117fac87e4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.drop_index('ix_schedule_processed_at')
        batch_op.drop_column('processed_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('processed_at', sa.DATETIME(), nullable=True))
        batch_op.create_index('ix_schedule_processed_at', ['processed_at'], unique=False)

    # ### end Alembic commands ###
