"""empty message

Revision ID: 5daf89550a20
Revises: be6bcf3bb65c
Create Date: 2023-03-09 23:17:09.120289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5daf89550a20'
down_revision = 'be6bcf3bb65c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hang', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reminded', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_hang_reminded'), ['reminded'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hang', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hang_reminded'))
        batch_op.drop_column('reminded')

    # ### end Alembic commands ###
