"""empty message

Revision ID: 64789e9258a4
Revises: 6dd152568b89
Create Date: 2023-03-19 16:55:57.121452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64789e9258a4'
down_revision = '6dd152568b89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hang', schema=None) as batch_op:
        batch_op.add_column(sa.Column('retry', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_hang_retry'), ['retry'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hang', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hang_retry'))
        batch_op.drop_column('retry')

    # ### end Alembic commands ###
