"""empty message

Revision ID: 78ca04337fc8
Revises: 1155b696e7f3
Create Date: 2023-02-28 22:23:53.633034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78ca04337fc8'
down_revision = '1155b696e7f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('week_of', sa.DateTime(), nullable=True),
    sa.Column('avails', sa.Text(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedule_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedule_processed'), ['processed'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedule_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedule_week_of'), ['week_of'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedule_week_of'))
        batch_op.drop_index(batch_op.f('ix_schedule_updated_at'))
        batch_op.drop_index(batch_op.f('ix_schedule_processed'))
        batch_op.drop_index(batch_op.f('ix_schedule_created_at'))

    op.drop_table('schedule')
    # ### end Alembic commands ###
