"""empty message

Revision ID: 9117fac87e4b
Revises: f565a781baf4
Create Date: 2023-04-17 17:44:12.148719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9117fac87e4b'
down_revision = 'f565a781baf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hang', schema=None) as batch_op:
        batch_op.add_column(sa.Column('friend_type', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_hang_friend_type'), ['friend_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hang', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hang_friend_type'))
        batch_op.drop_column('friend_type')

    # ### end Alembic commands ###
