"""empty message

Revision ID: a441b5cf8362
Revises: f6d7d25f09fe
Create Date: 2023-04-16 21:29:26.156751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a441b5cf8362'
down_revision = 'f6d7d25f09fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hang', schema=None) as batch_op:
        batch_op.add_column(sa.Column('connect_type', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_hang_connect_type'), ['connect_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hang', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hang_connect_type'))
        batch_op.drop_column('connect_type')

    # ### end Alembic commands ###
