"""empty message

Revision ID: be7826633929
Revises: a441b5cf8362
Create Date: 2023-04-17 14:09:28.069144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be7826633929'
down_revision = 'a441b5cf8362'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hang', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_field', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hang', schema=None) as batch_op:
        batch_op.drop_column('test_field')

    # ### end Alembic commands ###
