"""empty message

Revision ID: d2cec9a9d00c
Revises: be7826633929
Create Date: 2023-04-17 16:01:36.076013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2cec9a9d00c'
down_revision = 'be7826633929'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hang', schema=None) as batch_op:
        batch_op.drop_index('ix_hang_connect_type')
        batch_op.drop_column('connect_type')
        batch_op.drop_column('test_field')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hang', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_field', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('connect_type', sa.VARCHAR(length=255), nullable=True))
        batch_op.create_index('ix_hang_connect_type', ['connect_type'], unique=False)

    # ### end Alembic commands ###
