"""empty message

Revision ID: e96518b74a67
Revises: 223178149082
Create Date: 2023-07-03 16:39:27.807479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e96518b74a67'
down_revision = '223178149082'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=255), nullable=True),
    sa.Column('sid', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversation_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_sid'), ['sid'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_uid'), ['uid'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_updated_at'), ['updated_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_updated_at'))
        batch_op.drop_index(batch_op.f('ix_conversation_uid'))
        batch_op.drop_index(batch_op.f('ix_conversation_sid'))
        batch_op.drop_index(batch_op.f('ix_conversation_created_at'))

    op.drop_table('conversation')
    # ### end Alembic commands ###
