"""empty message

Revision ID: f6d7d25f09fe
Revises: f565a781baf4
Create Date: 2023-04-16 21:21:37.205766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6d7d25f09fe'
down_revision = 'f565a781baf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hang', schema=None) as batch_op:
        batch_op.add_column(sa.Column('connect_type', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_hang_connect_type'), ['connect_type'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('schedule_id')

    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.drop_index('ix_schedule_processed_at')
        batch_op.drop_column('processed_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('processed_at', sa.DATETIME(), nullable=True))
        batch_op.create_index('ix_schedule_processed_at', ['processed_at'], unique=False)

    with op.batch_alter_table('hang', schema=None) as batch_op:
        batch_op.add_column(sa.Column('schedule_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'schedule', ['schedule_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_hang_connect_type'))
        batch_op.drop_column('connect_type')

    # ### end Alembic commands ###
