"""empty message

Revision ID: f86803b21533
Revises: 5daf89550a20
Create Date: 2023-03-09 23:43:15.117702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f86803b21533'
down_revision = '5daf89550a20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hang', schema=None) as batch_op:
        batch_op.add_column(sa.Column('finalized_slot', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hang', schema=None) as batch_op:
        batch_op.drop_column('finalized_slot')

    # ### end Alembic commands ###
